import { LANGUAGES } from '@const/enums';

export const MIGRATION_STATES = {
  [LANGUAGES.russian]: {
    ableToTransfer: 'Вы можете перенести все свои активности из Strava в наш сервис. ',
    moreInfo: '1. Более подробная информация по ссылке (Bulk export)',
    archiveToEmail: '2. На электронную почту придет письмо со ссылкой на архив в формате .zip',
    whereToUpload: '3. Архив надо загрузить по кнопке ниже',
    removeMedia: 'Из архива будут вырезаны Ваши фото и видео, так как они могут весить очень много',
    processUnZipping: 'Процедура разархивирования и архивирования может занимать ощутимое время.',
    wifiConnection: 'Нужно хорошее интернет-соединение, лучше всего быстрый wi-fi',
    unzipping: 'Распаковываем архив',
    remove: 'Удаляем медиа',
    zipping: 'Запаковываем обратно',
    transfer: 'Отправляем архив на сервер',
    cleaning: 'Подчищаем файлы',
    successSending: 'Архив на сервере, теперь в зависимости от объема данных они будут обрабатываться до 10 минут',
    chooseArchive: 'Выбрать архив',
    unzip: 'Распаковываем...',
    removing: 'Удаляем медиа...',
    zip: 'Запаковываем...',
    sending: 'Отправляем...',
    clean: 'Подчищаем...',
    success: 'Успешно!',
    error: 'Ошибка',
  },
  [LANGUAGES.english]: {
    ableToTransfer: 'You can bring all your activities from Strava to Runich!',
    moreInfo: '1. Get detailed information',
    archiveToEmail: '2. You will receive an archive to your e-mail',
    whereToUpload: '3. The archive need to upload by clicking button below',
    removeMedia: 'Your media files will be removing from archive.',
    processUnZipping: 'It might takes significant amount of time',
    wifiConnection: 'Better to have fast connection, like wi-fi',
    unzipping: 'Unzipping',
    remove: 'Remove media',
    zipping: 'Zipping',
    transfer: 'Sending',
    cleaning: 'Cleaning files',
    successSending: 'Successfully sent',
    chooseArchive: 'Choose an archive',
    unzip: 'Unzipping...',
    removing: 'Removing media...',
    zip: 'Zipping...',
    sending: 'Sending...',
    clean: 'Cleaning...',
    success: 'Success!',
    error: 'Error',
  },
};
